theme: html5up-zerofour
params:
  enableSourceMaps: yes
  footer:
    contact_form:
      enabled: no
    links: {}

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      footnote: true
